<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	  <BaseOutputPath>$(SolutionDir)\bin\</BaseOutputPath>
	  <OutputPath>$(SolutionDir)\bin\</OutputPath>
	  <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	  <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
	  <UseCommonOutputDirectory>true</UseCommonOutputDirectory>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="26905_tumb_700X500.jpg" />
    <None Remove="BOEngineer\slider-3.jpg" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BL\BL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="photos\26905_tumb_700X500.jpg" />
    <Resource Include="photos\slider-3.jpg" />
  </ItemGroup>
</Project>
